
package vistas;

import java.awt.MouseInfo;
import java.awt.Point;


public class MenuPrincipal extends javax.swing.JFrame {
    int x,y;

    
    public MenuPrincipal() {
        initComponents();
        setSize(800,600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("MENU - Pastelería Sweet Creation");
        this.btnCerrar.setOpaque(true);
        setResizable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnFondo = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        btnNueva = new javax.swing.JButton();
        btnOrdenes = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnOfertas = new javax.swing.JButton();
        btnAdministrar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jpnUser = new javax.swing.JPanel();
        lblIDEmpleado = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblPfp = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblRango = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblBarra = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpnFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnMenu.setOpaque(false);

        btnNueva.setBackground(new java.awt.Color(186, 175, 142));
        btnNueva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNueva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_ingresar-nueva-orden.png"))); // NOI18N
        btnNueva.setBorderPainted(false);
        btnNueva.setOpaque(false);
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnOrdenes.setBackground(new java.awt.Color(186, 175, 142));
        btnOrdenes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOrdenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_ordenes-actuales.png"))); // NOI18N
        btnOrdenes.setBorderPainted(false);
        btnOrdenes.setOpaque(false);

        btnInventario.setBackground(new java.awt.Color(186, 175, 142));
        btnInventario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_inventario-disponible.png"))); // NOI18N
        btnInventario.setBorderPainted(false);
        btnInventario.setOpaque(false);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnOfertas.setBackground(new java.awt.Color(186, 175, 142));
        btnOfertas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOfertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_ofertas-disponibles.png"))); // NOI18N
        btnOfertas.setBorderPainted(false);
        btnOfertas.setOpaque(false);

        btnAdministrar.setBackground(new java.awt.Color(186, 175, 142));
        btnAdministrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdministrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_administrar-usuarios.png"))); // NOI18N
        btnAdministrar.setBorderPainted(false);
        btnAdministrar.setOpaque(false);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_cerrar-sesion.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenuLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAdministrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOfertas))
                    .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnOrdenes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNueva)))
                .addGap(24, 24, 24)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnMenuLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnCerrar))
                    .addComponent(btnAdministrar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpnFondo.add(jpnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 750, 420));

        jpnUser.setOpaque(false);
        jpnUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIDEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblIDEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jpnUser.add(lblIDEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 110, 20));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_peque.png"))); // NOI18N
        jpnUser.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 100, 40));

        lblPfp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User_peque.png"))); // NOI18N
        jpnUser.add(lblPfp, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 40, 40));

        lblNombre.setBackground(new java.awt.Color(102, 102, 102));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jpnUser.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 212, 24));

        lblRango.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblRango.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jpnUser.add(lblRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 82, 16));

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button.png"))); // NOI18N
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizarMousePressed(evt);
            }
        });
        jpnUser.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 0, 30, 20));

        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_x.png"))); // NOI18N
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });
        jpnUser.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 20, 20));

        lblBarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barra.png"))); // NOI18N
        lblBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBarraMouseDragged(evt);
            }
        });
        lblBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBarraMousePressed(evt);
            }
        });
        jpnUser.add(lblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jpnFondo.add(jpnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo1.png"))); // NOI18N
        lblFondo.setToolTipText("");
        jpnFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaActionPerformed

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblMinimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMousePressed

    private void lblBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_lblBarraMouseDragged

    private void lblBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblBarraMousePressed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdministrar;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnInventario;
    public javax.swing.JButton btnNueva;
    public javax.swing.JButton btnOfertas;
    public javax.swing.JButton btnOrdenes;
    private javax.swing.JPanel jpnFondo;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnUser;
    private javax.swing.JLabel lblBarra;
    private javax.swing.JLabel lblFondo;
    public javax.swing.JLabel lblIDEmpleado;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinimizar;
    public javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPfp;
    public javax.swing.JLabel lblRango;
    private javax.swing.JLabel lblSalir;
    // End of variables declaration//GEN-END:variables
}
