/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EjercicioParqueo;

import java.awt.Image;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cgali
 */
public class Parqueo extends javax.swing.JFrame {
    
    Usernames user = new Usernames();
    DefaultTableModel tabla;
    Object[] data = new Object[6];
    int fila=-1;
    DateTimeFormatter out = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");

    /**
     * Creates new form Parqueo
     */
    public Parqueo() {
        initComponents();
        setSize(800,560);
        setLocationRelativeTo(null);
        setTitle("Parqueadero Carnaval");
        
        //definicion de tabla con titulos
        tabla = (DefaultTableModel) tblDatos.getModel();
        
       
        //Configuracion del tamaño de iconos
        Image img = new ImageIcon("src/Imagenes/carro.png").getImage();
        ImageIcon iconoap = new ImageIcon (img.getScaledInstance(80, 71, Image.SCALE_SMOOTH));
        lblCarro.setIcon(iconoap);
        Image img2 = new ImageIcon("src/Imagenes/moto.png").getImage();
        ImageIcon icono2 = new ImageIcon (img2.getScaledInstance(80, 71, Image.SCALE_SMOOTH));
        lblMoto.setIcon(icono2);
        Image img3 = new ImageIcon("src/Imagenes/bici.png").getImage();
        ImageIcon icono3 = new ImageIcon (img3.getScaledInstance(80, 71, Image.SCALE_SMOOTH));
        lblBici.setIcon(icono3);
        Image imgb = new ImageIcon("src/Imagenes/lupa.png").getImage();
        ImageIcon iconobtn = new ImageIcon (imgb.getScaledInstance(20, 20, Image.SCALE_SMOOTH));
        btnBuscar.setIcon(iconobtn);
        
        //Obtener fecha y hora
        DateTimeFormatter fecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        lblFecha.setText(fecha.format(LocalDateTime.now()));
        DateTimeFormatter hora = DateTimeFormatter.ofPattern("HH:mm:ss");
        lblHora.setText(hora.format(LocalDateTime.now()));
        
        
        
    }
    public void limpiar (){
        txtPlaca.setText("");
        txtBuscar.setText("");
        btgTipov.clearSelection();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipov = new javax.swing.ButtonGroup();
        jpnFondo = new javax.swing.JPanel();
        jpnTipov = new javax.swing.JPanel();
        lblCarro = new javax.swing.JLabel();
        lblBici = new javax.swing.JLabel();
        lblMoto = new javax.swing.JLabel();
        rbtMoto = new javax.swing.JRadioButton();
        rbtCarro = new javax.swing.JRadioButton();
        rbtBici = new javax.swing.JRadioButton();
        jpnRegistro = new javax.swing.JPanel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        cmbEstado = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        jpnTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jpnSesion = new javax.swing.JPanel();
        btnSesion = new javax.swing.JButton();
        jpnExtras = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        lblH = new javax.swing.JLabel();
        lblF = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpnFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnTipov.setOpaque(false);

        btgTipov.add(rbtMoto);
        rbtMoto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtMoto.setText("Motocicleta");
        rbtMoto.setOpaque(false);

        btgTipov.add(rbtCarro);
        rbtCarro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtCarro.setText("Carro");
        rbtCarro.setOpaque(false);

        btgTipov.add(rbtBici);
        rbtBici.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtBici.setText("Bicicleta");
        rbtBici.setOpaque(false);

        javax.swing.GroupLayout jpnTipovLayout = new javax.swing.GroupLayout(jpnTipov);
        jpnTipov.setLayout(jpnTipovLayout);
        jpnTipovLayout.setHorizontalGroup(
            jpnTipovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTipovLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnTipovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnTipovLayout.createSequentialGroup()
                        .addComponent(lblMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnTipovLayout.createSequentialGroup()
                        .addComponent(rbtMoto)
                        .addGap(18, 18, 18)
                        .addComponent(rbtCarro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnTipovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnTipovLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbtBici))
                    .addComponent(lblBici, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTipovLayout.setVerticalGroup(
            jpnTipovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTipovLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnTipovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(lblBici, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(lblMoto, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(jpnTipovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtMoto)
                    .addComponent(rbtCarro)
                    .addComponent(rbtBici)))
        );

        jpnFondo.add(jpnTipov, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 110));

        jpnRegistro.setOpaque(false);

        lblPlaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPlaca.setText("Placa");

        btnRegistrar.setBackground(new java.awt.Color(0, 102, 204));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingreso", "Retiro" }));

        btnActualizar.setBackground(new java.awt.Color(0, 102, 204));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorderPainted(false);
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnRegistroLayout = new javax.swing.GroupLayout(jpnRegistro);
        jpnRegistro.setLayout(jpnRegistroLayout);
        jpnRegistroLayout.setHorizontalGroup(
            jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRegistroLayout.createSequentialGroup()
                .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnRegistroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblPlaca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpnRegistroLayout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpnRegistroLayout.setVerticalGroup(
            jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRegistroLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addContainerGap())
        );

        jpnFondo.add(jpnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 9, 210, 140));

        jpnTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros Abiertos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        jpnTabla.setOpaque(false);

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLACA", "TIPO VEHICULO", "HORA INGRESO", "HORA EGRESO", "ESTADO", "NO. REGISTRO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout jpnTablaLayout = new javax.swing.GroupLayout(jpnTabla);
        jpnTabla.setLayout(jpnTablaLayout);
        jpnTablaLayout.setHorizontalGroup(
            jpnTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTablaLayout.setVerticalGroup(
            jpnTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        jpnFondo.add(jpnTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 800, 310));

        jpnSesion.setOpaque(false);

        btnSesion.setBackground(new java.awt.Color(0, 102, 204));
        btnSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnSesion.setText("Cerrar Sesion");
        btnSesion.setBorderPainted(false);
        btnSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnSesionLayout = new javax.swing.GroupLayout(jpnSesion);
        jpnSesion.setLayout(jpnSesionLayout);
        jpnSesionLayout.setHorizontalGroup(
            jpnSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSesionLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(btnSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jpnSesionLayout.setVerticalGroup(
            jpnSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSesionLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnSesion)
                .addContainerGap())
        );

        jpnFondo.add(jpnSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 220, -1));

        jpnExtras.setOpaque(false);

        btnBuscar.setBackground(new java.awt.Color(0, 102, 204));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblH.setText("Hora:");

        lblF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblF.setText("Fecha:");

        lblHora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jpnExtrasLayout = new javax.swing.GroupLayout(jpnExtras);
        jpnExtras.setLayout(jpnExtrasLayout);
        jpnExtrasLayout.setHorizontalGroup(
            jpnExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jpnExtrasLayout.createSequentialGroup()
                            .addComponent(btnBuscar)
                            .addGap(18, 18, 18)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpnExtrasLayout.createSequentialGroup()
                            .addComponent(lblF)
                            .addGap(18, 18, 18)
                            .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpnExtrasLayout.createSequentialGroup()
                        .addComponent(lblH)
                        .addGap(22, 22, 22)
                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jpnExtrasLayout.setVerticalGroup(
            jpnExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblH)
                    .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblF)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jpnExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpnFondo.add(jpnExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 280, 130));

        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        lblFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpnFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionActionPerformed
        Login ventana = new Login();
        ventana.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnSesionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //Registro de la información en variables
        user.setPlaca(txtPlaca.getText());
        user.setHorain(out.format(LocalDateTime.now()));
        if (rbtMoto.isSelected()) {
            user.setTipov("Motocicleta");
        } else if (rbtCarro.isSelected()) {
            user.setTipov("Carro");
        } else if (rbtBici.isSelected()) {
            user.setTipov("Bicicleta");
        } else {
            user.setTipov("");
        }
        user.setFechaout("");
        if (cmbEstado.getSelectedItem().equals("Ingreso")) {
            user.setEstado("Abierto");
            user.setRegistro(user.getRegistro()+1);
                //Corroborar que no falte información
            if (user.getPlaca().length()==0 || user.getTipov().length()==0) {
                JOptionPane.showMessageDialog(this, "La información está incompleta");
            } else {
            //Añadir info a la tabla
            data[0] = user.getPlaca();
            data[1] = user.getTipov();
            data[2] = user.getHorain();
            data[3] = user.getFechaout();
            data[4] = user.getEstado();
            data[5] = user.getRegistro();
            tabla.addRow(data);
            limpiar();
            }
        } else{
            JOptionPane.showMessageDialog(this, "Para actualizar un vehículo, por favor seleccione buscar para poder realizar la acción");
        }
        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        fila = tblDatos.getSelectedRow();
        if (tblDatos.getSelectedRow() != -1) {
            txtBuscar.setText(tblDatos.getValueAt(fila, 0).toString());
            btnRegistrar.setEnabled(false);
            btnActualizar.setEnabled(true);
            txtPlaca.setEnabled(false);
            
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        //Verificar estado seleccionado para actualización
        if (cmbEstado.getSelectedItem().equals("Retiro")){
            user.cerrar();
            user.setFechaout(out.format(LocalDateTime.now()));
            if (fila !=-1) {
                tblDatos.setValueAt(user.getFechaout(), fila, 3);
                tblDatos.setValueAt(user.getEstado(), fila, 4);
            }
            limpiar();
            btnRegistrar.setEnabled(true);
            btnActualizar.setEnabled(false);
            txtPlaca.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Para registrar un reingreso, favor de ingresarlo como un nuevo vehículo");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parqueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipov;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSesion;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnExtras;
    private javax.swing.JPanel jpnFondo;
    private javax.swing.JPanel jpnRegistro;
    private javax.swing.JPanel jpnSesion;
    private javax.swing.JPanel jpnTabla;
    private javax.swing.JPanel jpnTipov;
    private javax.swing.JLabel lblBici;
    private javax.swing.JLabel lblCarro;
    private javax.swing.JLabel lblF;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblH;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblMoto;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JRadioButton rbtBici;
    private javax.swing.JRadioButton rbtCarro;
    private javax.swing.JRadioButton rbtMoto;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
